apiVersion: v1
kind: Service
metadata:
  name: lighthouse-frontend
  namespace: lighthouse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lighthouse
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
