apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lighthouse-api-pdb
  namespace: lighthouse
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lighthouse
      app.kubernetes.io/component: api
