apiVersion: v1
kind: ServiceAccount
metadata:
  name: lighthouse-api
  namespace: lighthouse
  annotations:
    iam.gke.io/gcp-service-account: lighthouse-sa@personal-project-289714.iam.gserviceaccount.com
